name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo build --release

      - name: Create/Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          prerelease: true
          make_latest: false
          files: target/release/*.exe